// Auto-generated schema initialization for Neon / Postgres databases
export const MIGRATION_STATEMENTS: string[] = [
    "CREATE TYPE \"public\".\"event_status\" AS ENUM(\u0027draft\u0027, \u0027published\u0027, \u0027cancelled\u0027);",
    "CREATE TYPE \"public\".\"expense_category\" AS ENUM(\u0027utilities\u0027, \u0027ministry\u0027, \u0027pastoral\u0027, \u0027admin\u0027, \u0027building\u0027, \u0027worship\u0027, \u0027welfare\u0027, \u0027other\u0027);",
    "CREATE TYPE \"public\".\"expense_status\" AS ENUM(\u0027draft\u0027, \u0027approved\u0027, \u0027paid\u0027);",
    "CREATE TYPE \"public\".\"finance_account_type\" AS ENUM(\u0027general\u0027, \u0027tithe\u0027, \u0027mission\u0027, \u0027building\u0027, \u0027welfare\u0027, \u0027special\u0027);",
    "CREATE TYPE \"public\".\"news_category\" AS ENUM(\u0027announcement\u0027, \u0027ministry\u0027, \u0027finance\u0027, \u0027pastoral\u0027);",
    "CREATE TYPE \"public\".\"news_status\" AS ENUM(\u0027draft\u0027, \u0027published\u0027, \u0027archived\u0027);",
    "CREATE TYPE \"public\".\"offering_category\" AS ENUM(\u0027tithe\u0027, \u0027general\u0027, \u0027mission\u0027, \u0027building\u0027, \u0027welfare\u0027, \u0027special\u0027);",
    "CREATE TYPE \"public\".\"offering_method\" AS ENUM(\u0027cash\u0027, \u0027transfer\u0027, \u0027check\u0027);",
    "CREATE TYPE \"public\".\"user_role\" AS ENUM(\u0027user\u0027, \u0027admin\u0027);",
    "CREATE TYPE \"public\".\"withdrawal_status\" AS ENUM(\u0027pending\u0027, \u0027approved\u0027, \u0027rejected\u0027, \u0027disbursed\u0027);",
    "CREATE TABLE \"budget_plans\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) NOT NULL,\r\n\t\"year\" integer NOT NULL,\r\n\t\"month\" integer,\r\n\t\"fundId\" integer,\r\n\t\"category\" varchar(80),\r\n\t\"plannedAmount\" numeric(15, 2) NOT NULL,\r\n\t\"notes\" text,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"church_events\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) DEFAULT \u0027demo-church\u0027 NOT NULL,\r\n\t\"authorId\" integer NOT NULL,\r\n\t\"title\" varchar(180) NOT NULL,\r\n\t\"summary\" varchar(280) NOT NULL,\r\n\t\"description\" text NOT NULL,\r\n\t\"startsAt\" timestamp NOT NULL,\r\n\t\"endsAt\" timestamp,\r\n\t\"location\" varchar(180),\r\n\t\"registrationUrl\" varchar(500),\r\n\t\"status\" \"event_status\" DEFAULT \u0027draft\u0027 NOT NULL,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"church_news\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) DEFAULT \u0027demo-church\u0027 NOT NULL,\r\n\t\"authorId\" integer NOT NULL,\r\n\t\"title\" varchar(180) NOT NULL,\r\n\t\"summary\" varchar(280) NOT NULL,\r\n\t\"body\" text NOT NULL,\r\n\t\"category\" \"news_category\" DEFAULT \u0027announcement\u0027 NOT NULL,\r\n\t\"status\" \"news_status\" DEFAULT \u0027draft\u0027 NOT NULL,\r\n\t\"publishedAt\" timestamp,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"church_profiles\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) NOT NULL,\r\n\t\"name\" varchar(180) NOT NULL,\r\n\t\"address\" text,\r\n\t\"phone\" varchar(20),\r\n\t\"email\" varchar(320),\r\n\t\"website\" varchar(500),\r\n\t\"pastorName\" varchar(120),\r\n\t\"assistantPastorName\" varchar(120),\r\n\t\"treasurerName\" varchar(120),\r\n\t\"bankName\" varchar(120),\r\n\t\"bankAccount\" varchar(30),\r\n\t\"bankAccountName\" varchar(120),\r\n\t\"fiscalYearStartMonth\" integer DEFAULT 1 NOT NULL,\r\n\t\"logoUrl\" varchar(500),\r\n\t\"setupCompleted\" boolean DEFAULT false NOT NULL,\r\n\t\"motto\" varchar(280),\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL,\r\n\tCONSTRAINT \"church_profiles_churchId_unique\" UNIQUE(\"churchId\")\r\n);",
    "CREATE TABLE \"expenses\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) NOT NULL,\r\n\t\"amount\" numeric(15, 2) NOT NULL,\r\n\t\"category\" \"expense_category\" DEFAULT \u0027other\u0027 NOT NULL,\r\n\t\"fundId\" integer,\r\n\t\"description\" varchar(280) NOT NULL,\r\n\t\"details\" text,\r\n\t\"expenseDate\" timestamp DEFAULT now() NOT NULL,\r\n\t\"payee\" varchar(120),\r\n\t\"receiptRef\" varchar(120),\r\n\t\"status\" \"expense_status\" DEFAULT \u0027approved\u0027 NOT NULL,\r\n\t\"approvedBy\" integer,\r\n\t\"recordedBy\" integer NOT NULL,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"finance_accounts\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) NOT NULL,\r\n\t\"name\" varchar(120) NOT NULL,\r\n\t\"type\" \"finance_account_type\" DEFAULT \u0027general\u0027 NOT NULL,\r\n\t\"balance\" numeric(15, 2) DEFAULT \u00270\u0027 NOT NULL,\r\n\t\"description\" text,\r\n\t\"isActive\" boolean DEFAULT true NOT NULL,\r\n\t\"sortOrder\" integer DEFAULT 0 NOT NULL,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"offerings\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) NOT NULL,\r\n\t\"amount\" numeric(15, 2) NOT NULL,\r\n\t\"category\" \"offering_category\" DEFAULT \u0027general\u0027 NOT NULL,\r\n\t\"fundId\" integer,\r\n\t\"donorName\" varchar(120),\r\n\t\"donorMemberId\" integer,\r\n\t\"receiptDate\" timestamp DEFAULT now() NOT NULL,\r\n\t\"method\" \"offering_method\" DEFAULT \u0027cash\u0027 NOT NULL,\r\n\t\"reference\" varchar(120),\r\n\t\"notes\" text,\r\n\t\"recordedBy\" integer NOT NULL,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"users\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"openId\" varchar(64) NOT NULL,\r\n\t\"name\" text,\r\n\t\"email\" varchar(320),\r\n\t\"loginMethod\" varchar(64),\r\n\t\"role\" \"user_role\" DEFAULT \u0027user\u0027 NOT NULL,\r\n\t\"churchRole\" varchar(20),\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"lastSignedIn\" timestamp DEFAULT now() NOT NULL,\r\n\tCONSTRAINT \"users_openId_unique\" UNIQUE(\"openId\")\r\n);",
    "CREATE TABLE \"withdrawal_requests\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) NOT NULL,\r\n\t\"amount\" numeric(15, 2) NOT NULL,\r\n\t\"purpose\" varchar(280) NOT NULL,\r\n\t\"details\" text,\r\n\t\"fundId\" integer,\r\n\t\"requestedBy\" integer NOT NULL,\r\n\t\"requestDate\" timestamp DEFAULT now() NOT NULL,\r\n\t\"status\" \"withdrawal_status\" DEFAULT \u0027pending\u0027 NOT NULL,\r\n\t\"approvedBy\" integer,\r\n\t\"approvalDate\" timestamp,\r\n\t\"approvalNote\" text,\r\n\t\"rejectionReason\" text,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TYPE \"public\".\"member_status\" AS ENUM(\u0027active\u0027, \u0027inactive\u0027, \u0027pending\u0027);",
    "CREATE TYPE \"public\".\"offering_status\" AS ENUM(\u0027active\u0027, \u0027voided\u0027);",
    "ALTER TYPE \"public\".\"expense_status\" ADD VALUE IF NOT EXISTS \u0027voided\u0027;",
    "CREATE TABLE \"members\" (\r\n  \"id\" serial PRIMARY KEY NOT NULL,\r\n  \"churchId\" varchar(64) NOT NULL,\r\n  \"name\" varchar(180) NOT NULL,\r\n  \"phone\" varchar(30),\r\n  \"email\" varchar(320),\r\n  \"status\" \"member_status\" DEFAULT \u0027active\u0027 NOT NULL,\r\n  \"avatarUrl\" varchar(500),\r\n  \"notes\" text,\r\n  \"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n  \"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"notifications\" (\r\n  \"id\" serial PRIMARY KEY NOT NULL,\r\n  \"churchId\" varchar(64) NOT NULL,\r\n  \"userId\" integer NOT NULL,\r\n  \"type\" varchar(40) NOT NULL,\r\n  \"title\" varchar(180) NOT NULL,\r\n  \"description\" text,\r\n  \"link\" varchar(500),\r\n  \"readAt\" timestamp,\r\n  \"createdAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE \"audit_logs\" (\r\n  \"id\" serial PRIMARY KEY NOT NULL,\r\n  \"churchId\" varchar(64) NOT NULL,\r\n  \"userId\" integer NOT NULL,\r\n  \"action\" varchar(40) NOT NULL,\r\n  \"entity\" varchar(80) NOT NULL,\r\n  \"entityId\" integer,\r\n  \"metadata\" jsonb,\r\n  \"createdAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "ALTER TABLE \"offerings\" ADD COLUMN \"status\" \"offering_status\" DEFAULT \u0027active\u0027 NOT NULL;",
    "ALTER TABLE \"offerings\" ADD COLUMN \"voidedAt\" timestamp;",
    "CREATE INDEX \"members_church_idx\" ON \"members\" USING btree (\"churchId\");",
    "CREATE INDEX \"notifications_user_idx\" ON \"notifications\" USING btree (\"churchId\", \"userId\", \"createdAt\");",
    "CREATE INDEX \"audit_logs_entity_idx\" ON \"audit_logs\" USING btree (\"churchId\", \"entity\", \"entityId\", \"createdAt\");",
    "-- Weekly offering counting and reconciliation.\r\n--\r\n-- Generated with drizzle-kit by diffing drizzle/schema.ts against the previous\r\n-- committed schema, then made re-runnable: this repo\u0027s 0001 migration is not\r\n-- registered in meta/_journal.json, so migrations here are applied by hand and\r\n-- may be retried. Additive only: no existing table or column is altered.\r\n\r\nDO $$ BEGIN\r\n  CREATE TYPE \"public\".\"bank_record_type\" AS ENUM(\u0027transfer_in\u0027, \u0027cash_deposit\u0027);\r\nEXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN\r\n  CREATE TYPE \"public\".\"cash_kind\" AS ENUM(\u0027note\u0027, \u0027coin\u0027);\r\nEXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN\r\n  CREATE TYPE \"public\".\"counting_session_status\" AS ENUM(\u0027counting\u0027, \u0027counted\u0027, \u0027verified\u0027, \u0027posted\u0027, \u0027closed\u0027);\r\nEXCEPTION WHEN duplicate_object THEN null; END $$;",
    "DO $$ BEGIN\r\n  CREATE TYPE \"public\".\"session_document_kind\" AS ENUM(\u0027count_sheet\u0027, \u0027envelope_photo\u0027, \u0027deposit_slip\u0027, \u0027transfer_slip\u0027, \u0027passbook_page\u0027, \u0027deduction_receipt\u0027, \u0027other\u0027);\r\nEXCEPTION WHEN duplicate_object THEN null; END $$;",
    "CREATE TABLE IF NOT EXISTS \"bank_records\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"sessionId\" integer NOT NULL,\r\n\t\"churchId\" varchar(64) DEFAULT \u0027demo-church\u0027 NOT NULL,\r\n\t\"type\" \"bank_record_type\" NOT NULL,\r\n\t\"amount\" numeric(15, 2) NOT NULL,\r\n\t\"transferredBy\" integer,\r\n\t\"transferredByName\" varchar(180),\r\n\t\"bankRef\" varchar(120),\r\n\t\"occurredAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"passbookMatched\" boolean DEFAULT false NOT NULL,\r\n\t\"passbookDate\" timestamp,\r\n\t\"matchedBy\" integer,\r\n\t\"recordedBy\" integer NOT NULL,\r\n\t\"notes\" text,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE IF NOT EXISTS \"cash_counts\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"sessionId\" integer NOT NULL,\r\n\t\"denomination\" numeric(8, 2) NOT NULL,\r\n\t\"kind\" \"cash_kind\" NOT NULL,\r\n\t\"quantity\" integer DEFAULT 0 NOT NULL,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE IF NOT EXISTS \"counting_sessions\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"churchId\" varchar(64) DEFAULT \u0027demo-church\u0027 NOT NULL,\r\n\t\"serviceDate\" timestamp NOT NULL,\r\n\t\"serviceRound\" integer DEFAULT 1 NOT NULL,\r\n\t\"serviceName\" varchar(120),\r\n\t\"status\" \"counting_session_status\" DEFAULT \u0027counting\u0027 NOT NULL,\r\n\t\"countedBy\" integer NOT NULL,\r\n\t\"countSubmittedAt\" timestamp,\r\n\t\"verifiedBy\" integer,\r\n\t\"verifiedAt\" timestamp,\r\n\t\"postedBy\" integer,\r\n\t\"postedAt\" timestamp,\r\n\t\"closedAt\" timestamp,\r\n\t\"varianceNote\" text,\r\n\t\"varianceApprovedBy\" integer,\r\n\t\"notes\" text,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE IF NOT EXISTS \"offering_envelopes\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"sessionId\" integer NOT NULL,\r\n\t\"churchId\" varchar(64) DEFAULT \u0027demo-church\u0027 NOT NULL,\r\n\t\"envelopeNo\" varchar(30),\r\n\t\"memberId\" integer,\r\n\t\"donorName\" varchar(180),\r\n\t\"isAnonymous\" boolean DEFAULT false NOT NULL,\r\n\t\"category\" \"offering_category\" DEFAULT \u0027general\u0027 NOT NULL,\r\n\t\"fundId\" integer,\r\n\t\"method\" \"offering_method\" DEFAULT \u0027cash\u0027 NOT NULL,\r\n\t\"amount\" numeric(15, 2) NOT NULL,\r\n\t\"reference\" varchar(120),\r\n\t\"notes\" text,\r\n\t\"recordedBy\" integer NOT NULL,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE IF NOT EXISTS \"session_deductions\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"sessionId\" integer NOT NULL,\r\n\t\"churchId\" varchar(64) DEFAULT \u0027demo-church\u0027 NOT NULL,\r\n\t\"purpose\" varchar(200) NOT NULL,\r\n\t\"reason\" text NOT NULL,\r\n\t\"amount\" numeric(15, 2) NOT NULL,\r\n\t\"paidTo\" varchar(180) NOT NULL,\r\n\t\"requestedBy\" integer NOT NULL,\r\n\t\"approvedBy\" integer,\r\n\t\"approvedAt\" timestamp,\r\n\t\"category\" \"expense_category\" DEFAULT \u0027other\u0027 NOT NULL,\r\n\t\"fundId\" integer,\r\n\t\"expenseId\" integer,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL,\r\n\t\"updatedAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "CREATE TABLE IF NOT EXISTS \"session_documents\" (\r\n\t\"id\" serial PRIMARY KEY NOT NULL,\r\n\t\"sessionId\" integer NOT NULL,\r\n\t\"churchId\" varchar(64) DEFAULT \u0027demo-church\u0027 NOT NULL,\r\n\t\"kind\" \"session_document_kind\" DEFAULT \u0027other\u0027 NOT NULL,\r\n\t\"fileName\" varchar(255) NOT NULL,\r\n\t\"mimeType\" varchar(120),\r\n\t\"fileSize\" integer,\r\n\t\"driveFileId\" varchar(180),\r\n\t\"fileUrl\" varchar(600),\r\n\t\"drivePath\" varchar(300),\r\n\t\"deductionId\" integer,\r\n\t\"bankRecordId\" integer,\r\n\t\"uploadedBy\" integer NOT NULL,\r\n\t\"createdAt\" timestamp DEFAULT now() NOT NULL\r\n);",
    "ALTER TABLE \"members\" ADD COLUMN IF NOT EXISTS \"envelopeNo\" varchar(30);",
    "ALTER TABLE \"offerings\" ADD COLUMN IF NOT EXISTS \"sessionId\" integer;"
];

export async function runSchemaInit(client: any) {
  for (const stmt of MIGRATION_STATEMENTS) {
    try {
      await client.unsafe(stmt);
    } catch (err: any) {
      if (
        err.message?.includes("already exists") ||
        err.message?.includes("duplicate")
      ) {
        continue;
      }
      console.warn("[Schema Init Warning]", err.message);
    }
  }
}
